version: "3.9"
services:
  # API Gateway
  app:
   
    ports:
      - 8080:80
    image: aaveline/node:v1
    volumes:
      - .:/usr/src/app

az containerapp env create \
  --name aymericcontainerappenv \
  --resource-group aymericrg \
  --location westeurope


az containerapp create \
  --name aymericcontainerapp \
  --resource-group aymericrg \
  --environment  aymericcontainerappenv \
  --image docker.io/aaveline/node:v1 \
  --target-port 80 \
  --ingress 'external' \
  --query properties.configuration.ingress.fqdn

// Create fileshare in stoageaccount
az containerapp env storage set --name managedEnvironment-aymericrg-b09b --resource-group aymericrg     --storage-name aymericstorageaccount     --azure-file-account-name aymericstorageaccount     --azure-file-account-key uc05hhF6tqrRbXNe/I48+1W5z7KHyKdFFbony4fg4dK/8wCdyZeGU0VPpsqTdlG3eCXPAl1u7iUb+AStvb8n/Q==     --azure-file-share-name aymericstoragename     --access-mode ReadWrite


az containerapp show -n aymericcontainerapp -g aymericrg -o yaml > app.yaml
// Update app.yml with volume
/*

      volumeMounts:
      - volumeName: azure-files-volume
        mountPath: /my-files
    volumes:
    - name: azure-files-volume
      storageType: AzureFile
      storageName: mystorage

      */
az containerapp update --name aymericcontainerapp -g aymericrg --yaml app.yaml

az containerapp show 
az containerapp env storage set --name aymericcontainerapp --resource-group aymericrg \
    --storage-name aymericstorageaccount \
    --azure-file-account-name aymericstorageaccount \
    --azure-file-account-key uc05hhF6tqrRbXNe/I48+1W5z7KHyKdFFbony4fg4dK/8wCdyZeGU0VPpsqTdlG3eCXPAl1u7iUb+AStvb8n/Q== \
    --azure-file-share-name aymericstoragename \
    --access-mode ReadWrite